name: Sync LAU settlements GeoJSON

on:
  schedule:
    - cron: '0 3 * * *'   # Daily at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download latest GeoJSON
        run: |
          curl -L \
          https://gist.githubusercontent.com/czinkos/bedb669ca606627780483e1949ad4bb4/raw/hungary_settlements.geojson \
          -o settlements.geojson

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add settlements.geojson

          if ! git diff --cached --quiet; then
            git commit -m "Sync LAU settlements GeoJSON"
            git push
          fi